_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  # temporary for mac
  #DEVICE: "cpu"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  FP16:
    ENABLED: True
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 2
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
  FEWX_BASELINE: True
  WITH_ALIGNMENT: False
OUTPUT_DIR: './output/fsod/prototype_training_bdd_resnet101_stage_1'
INPUT:
  # need to change
  FS:
    SUPPORT_WAY: 10
    SUPPORT_SHOT: 5
    USE_SUPPORT_SHOT_RATIO: False
    SUPPORT_SHOT_RATIO: 0.2
  # change to CoCo dataset setting
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("bdd_trainval_all",)
  TEST: ("bdd_test_all",)
  TEST_KEEPCLASSES: 'all'
  # need to change
  TEST_SHOTS: (3,5)
SOLVER:
  IMS_PER_BATCH: 4 #8
  BASE_LR: 0.002
  STEPS: (15000, 20000)
  MAX_ITER: 20001
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 2000
  HEAD_LR_FACTOR: 2.0
  GRADIENT_ACCUMULATION_STEPS: 2
TEST:
  EVAL_PERIOD: 20000
