_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "./output/fsod/prototype_training_bdd_resnet101_stage_1/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 2
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
  FEWX_BASELINE: False
  WITH_ALIGNMENT: False
OUTPUT_DIR: './output/fsod/prototype_training_bdd_resnet101_stage_2'
INPUT:
  FS:
    SUPPORT_WAY: 10
    SUPPORT_SHOT: 5
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ("bdd_trainval_all",)
  TEST: ("bdd_test_all",)
  TEST_KEEPCLASSES: 'all'
  TEST_SHOTS: (3,5)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (7500, 10000)
  MAX_ITER: 10001
  WARMUP_ITERS: 1500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 2000
  GRADIENT_ACCUMULATION_STEPS: 2
TEST:
  EVAL_PERIOD: 10000
